//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FromLocalsToLocals.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VendorTypeEnum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VendorTypeEnum() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FromLocalsToLocals.Resources.VendorTypeEnum", typeof(VendorTypeEnum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beverages.
        /// </summary>
        public static string Beverages {
            get {
                return ResourceManager.GetString("Beverages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car repair.
        /// </summary>
        public static string CarRepair {
            get {
                return ResourceManager.GetString("CarRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        public static string Clothing {
            get {
                return ResourceManager.GetString("Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        public static string Electronics {
            get {
                return ResourceManager.GetString("Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowers.
        /// </summary>
        public static string Flowers {
            get {
                return ResourceManager.GetString("Flowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footwear.
        /// </summary>
        public static string Footwear {
            get {
                return ResourceManager.GetString("Footwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rural tourism.
        /// </summary>
        public static string RuralTourism {
            get {
                return ResourceManager.GetString("RuralTourism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stationery.
        /// </summary>
        public static string Stationery {
            get {
                return ResourceManager.GetString("Stationery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys.
        /// </summary>
        public static string Toys {
            get {
                return ResourceManager.GetString("Toys", resourceCulture);
            }
        }
    }
}
